### PR TITLE
Estimate robot angle

### LINKED ISSUE #86: Estimate robot angle (fix rate of change)

### PR DESCRIPTION
**Pull request by jwtan5**
- Updated estimateRobotAngle
- Moved to Patches

### CODE REVIEW

**Comment by sarthakahuja11** [comment]
@jwtan5 Do you feel this is ready to be merged now?

**Review by sarthakahuja11 — COMMENTED** [review]
Looks, good. need to see if we will subsequently change main.cpp later

**Comment by jwtan5** [comment]
yes it is

**Review by sarthakahuja11 — APPROVED** [review]
Done, merged latest devel

**Pull request merged**
