### PR TITLE
Create design_logs.md

### PR DESCRIPTION
**Pull request by addy1997**

### CODE REVIEW

**Comment by sarthakahuja11** [comment]
@addy1997 https://github.com/CAT-Technologies/GrocerEase/blob/devel/utils/HardwareUpdates_LogFile.md

This has exactly what you wanted. You can update it if you did something extra and then probably format it as a table or so as you did in changelog? As then would be easier for David and us to edit it.

Let me know if you can do that

**Comment by addy1997** [comment]
> @addy1997 https://github.com/CAT-Technologies/GrocerEase/blob/devel/utils/HardwareUpdates_LogFile.md
> 
> This has exactly what you wanted. You can update it if you did something extra and then probably format it as a table or so as you did in changelog? As then would be easier for David and us to edit it.
> 
> Let me know if you can do that

Not quite sure, what he(Porr and Bailey) wanted but they just told me to maintain a record/entry sort of a thing for Hardware.

**Comment by sarthakahuja11** [comment]
Did you open the file I created? Is it different from what he wants? You can update  it too with some extra hardware-related work you did

**Comment by addy1997** [comment]
> Did you open the file I created? Is it different from what he wants? You can update it too with some extra hardware-related work you did

Nah! it's the same thing. Jan Hendrik initiated this *LOG* idea. We will ask him on Wednesday.

**Comment by sarthakahuja11** [comment]
Yes, no need to ask him, if you are happy with the file, feel free to format it and add it to whatever folder you want.

You are better in  github formatting and all, so add more content or just make it more readable/editable using tables or so

**Pull request merged**
