### PR TITLE
Flowchart for GPIO added (linked issue #22)

### LINKED ISSUE #45: Add license to the flowchart codes.

### PR DESCRIPTION
**Pull request by addy1997**

### CODE REVIEW

**Comment by sarthakahuja11** [comment]
Can I generate the flowchart live by using the code in txt file? Using that website used....

**Comment by addy1997** [comment]
Yes, you can do.

**Comment by sarthakahuja11** [comment]
okay, let me go through in detail while generating it

**Comment by addy1997** [comment]
code analysis
Screenshot 2022-02-23 at 12 26 00

**Comment by sarthakahuja11** [comment]
1. In this flow diagram, do you prioritize the right IR sensor over the left one? Like we check right first and then left?
Or should we incorporate a way where we check both together and 'OR' the results of both sensors? 
Or does this exactly do that and checking the right one first would not matter much in real-time?


2. Also, this was directly drawn from the GPIO.cpp file, or does some part of this flow diagram still needs to be converted in code/implementation?

**Comment by addy1997** [comment]
> 1. In this flow diagram, do you prioritize the right IR sensor over the left one? Like we check right first and then left?
>        Or should we incorporate a way where we check both together and 'OR' the results of both sensors?
>        Or does this exactly do that and checking the right one first would not matter much in real-time?
> 
>     2. Also, this was directly drawn from the GPIO.cpp file, or does some part of this flow diagram still needs to be converted in code/implementation?

1. Currently, its first checking the right IR sensor and then the left one. Yeah, it matters how we implement it in real time. WE should incorporate a way to check both the sensors at a time and then decide on the basis of the o/p of both sensors.

2. This code was directly drawn from the file David wrote.

**Comment by sarthakahuja11** [comment]
Yes, let's keep your last line in mind (point 1) while we implement it, especially. Probably note it down as a potential improvement as so. 

Thanks for the clarification.

**Comment by addy1997** [comment]
okay

**Pull request merged**
