### PR TITLE
adding code of conduct

### PR DESCRIPTION
**Pull request by sarthakahuja11**

### CODE REVIEW

**Comment by addy1997** [comment]
@sarthakahuja11, thanks for the PR. Please check [this](https://app.codacy.com/gh/CAT-Technologies/GrocerEase/pullRequest?prid=9091726)

**Comment by sarthakahuja11** [comment]
I actually just followed the steps here - https://github.com/CAT-Technologies/GrocerEase/community

Then I just added it from here as needed - directly. Have a look.

Do you feel we should really work about codacy checks here as it is just a text file anyway?

**Comment by addy1997** [comment]
> I actually just followed the steps here - https://github.com/CAT-Technologies/GrocerEase/community
> 
> Then I just added it from here as needed - directly. Have a look.
> 
> Do you feel we should really work about codacy checks here as it is just a text file anyway?

File name isn't that big an issue but I would like to stick to *codacy* guidelines.

**Comment by sarthakahuja11** [comment]
Do Codacy guidelines even check .md files like this one? 

As this really has no code as such, just text inside as per Github default Community practices

**Comment by sarthakahuja11** [comment]
There wasnt a need to merge with the codacy failing, I wanted to ask if you could disable codacy checking the .md files or non code related files?

**Comment by addy1997** [comment]
> There wasnt a need to merge with the codacy failing, I wanted to ask if you could disable codacy checking the .md files or non code related files?

Nevermind, it's done. Anyways, codacy matters more for code and least for the .md files.

**Pull request merged**
