### PR TITLE
assigning files to correct folders

### LINKED ISSUE #99: Issues with the main_program
See the issues below.

### LINKED ISSUE #113: Grocerease code finalise with main

### PR DESCRIPTION
**Pull request by sarthakahuja11**
main.cpp needs to reviewed by @jwtan5  - what he wants to keep and what not
also he needs to review the patches files - if all have been used
@addy1997 needs to put callback src folder at  a better place - explaining/referencing location in wiki

### CODE REVIEW

**Comment by sarthakahuja11** [comment]
@addy1997  pls edit src/cmakelists to ensure build isnt affected. adding gpio.h/.cpp has no sense as they are now a part of cart, unless you feel the repo wont build without them

**Comment by sarthakahuja11** [comment]
> main.cpp needs to reviewed by @jwtan5 - what he wants to keep and what not also he needs to review the patches files - if all have been used @addy1997 needs to put callback src folder at a better place - explaining/referencing location in wiki

@jwtan5  any updates, please?
@addy1997 is waiting for you

**Comment by jwtan5** [comment]
@sarthakahuja11 I'd suggest renaming ComputeAngle.cpp in src to ComputeAngle_testing.cpp, as it's not deployed in the main program.

**Comment by addy1997** [comment]
@sarthakahuja11, the least I can say is to close this PR as it's of no use if it has no major changes.

**Comment by sarthakahuja11** [comment]
@addy1997 can this be fixed if we add the groceries.CPP or .h files?
Or I'll just do cart files only?

image

**Comment by AzvenusK** [comment]
Are we still merging this PR?

**Comment by sarthakahuja11** [comment]
@AzvenusK  not really, will make one final edit n close it

**Pull request closed without merging**
