### PR TITLE
Motor testing

### LINKED ISSUE #88: Motor testing
**Describe the Test**
Motor testing cart

**To Reproduce**
Run motor_testing.cpp

**Expected behavior**
Checks the required value between 0 to 255 to make the cart move

**Additional context**
NA

### PR DESCRIPTION
**Pull request by jwtan5**
- Added motor testing & calibration

### CODE REVIEW

**Comment by sarthakahuja11** [comment]
Will do the review shortly

**Review by sarthakahuja11 — APPROVED** [review]
Made final changes

**Comment by addy1997** [comment]
Sorry for the unsolicited comment.
Thanks for the changes @sarthakahuja11.  
Have the changes been reviewed by @jwtan5 ? (specially line 95 and 96)

**Comment by sarthakahuja11** [comment]
> Sorry for the unsolicited comment. Thanks for the changes @sarthakahuja11. Have the changes been reviewed by @jwtan5 ? (specially line 95 and 96)

Yes

**Pull request merged**
