### PR TITLE
Mobile app with ble

### LINKED ISSUE #32: Mobile app complete with planned functionalities
Refer Discussion sections for initial links
Follow process to get app up and running

### PR DESCRIPTION
**Pull request by sarthakahuja11**
Merging final mobile app

### CODE REVIEW

**Comment by sarthakahuja11** [comment]
https://github.com/CAT-Technologies/GrocerEase/issues/32

**Comment by sarthakahuja11** [comment]
Codacy issues all of minor severity, can be ignored

**Comment by addy1997** [comment]
@sarthakahuja11, I am ignoring the codacy issues in the interest of time.  PR approved.

**Comment by sarthakahuja11** [comment]
> @sarthakahuja11, I am ignoring the codacy issues in the interest of time.  PR approved.

You have admin access to codacy for this repo, you can explicitly ignore files too improve our analysis

**Pull request merged**
