### PR TITLE
initial template for the project [VERY VERY IMPORTANT]

### LINKED ISSUE #48: build system for the project.
1. Cmake: https://cmake.org/
2. Make: obsolete so not preferred
3. Colcon: https://colcon.readthedocs.io/en/released/

### PR DESCRIPTION
**Pull request by addy1997**

### CODE REVIEW

**Comment by sarthakahuja11** [comment]
Is everything building here perfectly?

**Comment by sarthakahuja11** [comment]
@addy1997 If this builds perfectly in your local, are you thinking to add more commits to this branch or want to test it more regressively?

**Review by sarthakahuja11 — APPROVED** [review]
Looks good, testing pending

**Comment by addy1997** [comment]
> @addy1997 If this builds perfectly in your local, are you thinking to add more commits to this branch or want to test it more regressively?

take 1 week if you need but please go through each and every minute detail of the build (only if you have time) coz this is the foundation and we can't get it wrong.

**Comment by sarthakahuja11** [comment]
> > @addy1997 If this builds perfectly in your local, are you thinking to add more commits to this branch or want to test it more regressively?
> 
> take 1 week if you need but please go through each and every minute detail of the build (only if you have time) coz this is the foundation and we can't get it wrong.

Yes okay, I agree let's first try to finish all encapsulation + SOLID and then we can add those commits to this branch, test it more and then only merge. 

Let's keep the PR open till we add more stuff to develop. Then merge latest develop to  this branch, and then test more. I will do the last few things so don't worry about it.

**Comment by addy1997** [comment]
Alright!

**Comment by addy1997** [comment]
I want an in-depth review on this, @sarthakahuja11. 

Please take ample time to go thorugh every small thing.

**Comment by sarthakahuja11** [comment]
Looks, okay but we don't have main_program.cpp and write_motor.cpp. 

I think there is a way and you can add in the cmake to ignore building them. Do you know that?

Just because I don't want any code versions to go missing if you completely remove it from the repository altogether in this branch. What do you think?

**Comment by addy1997** [comment]
> Looks, okay but we don't have main_program.cpp and write_motor.cpp.
> 
> I think there is a way and you can add in the cmake to ignore building them. Do you know that?
> 
> Just because I don't want any code versions to go missing if you completely remove it from the repository altogether in this branch. What do you think?

In the end, there will be just 1 or 2 .cpp files in the src directory. Again, it's your call, those files are still there in devel. If you want to include them, feel free to do so, I don't have any issues. Just make sure the repository structure is not compromised.

**Comment by sarthakahuja11** [comment]
@addy1997 

> > Looks, okay but we don't have main_program.cpp and write_motor.cpp.
> > I think there is a way and you can add in the cmake to ignore building them. Do you know that?
> > Just because I don't want any code versions to go missing if you completely remove it from the repository altogether in this branch. What do you think?
> 
> In the end, there will be just 1 or 2 .cpp files in the src directory. Again, it's your call, those files are still there in devel. If you want to include them, feel free to do so, I don't have any issues. Just make sure the repository structure is not compromised.

Here, you said "those files are still on devel" - but as you deleted these files from your branch and when you **merge** this branch onto devel, would those two files get removed from devel too? And we completely lose the files (unless we do the messy revert commits) ? Or is it not like that? Let me know if you feel if this might happen or I am wrong?

**Comment by addy1997** [comment]
I care the least' bout those two files. My primary focus is the rssi and
the main code. You can maintain those files as a backup in a folder and
push them after the merging is done.

**Comment by sarthakahuja11** [comment]
https://github.com/CAT-Technologies/GrocerEase/commit/c5ecd1fbefc18dd7cc1ca9cba96dabf59d589504


Try referencing last changes as we discussed before you press merge PR.

I thought you forgot patches and had to double revert the PR, but all is fine now

**Comment by addy1997** [comment]
Yeah, sorry about that. I had pulled all the changes upstream. Anyways,
it's done now

**Pull request merged**
